import { Category } from '@/types';

export const DEFAULT_EXPENSE_CATEGORIES: Omit<Category, 'id' | 'createdAt'>[] = [
  {
    name: 'อาหาร',
    type: 'expense',
    icon: '🍔',
    color: 'category-food',
    sortOrder: 1,
    isSystem: true,
  },
  {
    name: 'ของใช้',
    type: 'expense',
    icon: '🛒',
    color: 'category-shopping',
    sortOrder: 2,
    isSystem: true,
  },
  {
    name: 'การจราจร',
    type: 'expense',
    icon: '🚌',
    color: 'category-transport',
    sortOrder: 3,
    isSystem: true,
  },
  {
    name: 'เดท',
    type: 'expense',
    icon: '🍽️',
    color: 'category-social',
    sortOrder: 4,
    isSystem: true,
  },
  {
    name: 'ทางการแพทย์',
    type: 'expense',
    icon: '🏥',
    color: 'category-health',
    sortOrder: 5,
    isSystem: true,
  },
  {
    name: 'ครอบครัว',
    type: 'expense',
    icon: '👨‍👩‍👧',
    color: 'category-family',
    sortOrder: 6,
    isSystem: true,
  },
  {
    name: 'นันทนาการ',
    type: 'expense',
    icon: '🎬',
    color: 'category-entertainment',
    sortOrder: 7,
    isSystem: true,
  },
  {
    name: 'ทางสังคม',
    type: 'expense',
    icon: '🥂',
    color: 'category-social',
    sortOrder: 8,
    isSystem: true,
  },
  {
    name: 'ที่อยู่อาศัย',
    type: 'expense',
    icon: '🏠',
    color: 'category-housing',
    sortOrder: 9,
    isSystem: true,
  },
  {
    name: 'สื่อสาร',
    type: 'expense',
    icon: '📱',
    color: 'category-communication',
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'เสื้อผ้า',
    type: 'expense',
    icon: '👕',
    color: 'category-clothing',
    sortOrder: 11,
    isSystem: true,
  },
  {
    name: 'อื่นๆ',
    type: 'expense',
    icon: '📦',
    color: 'category-other',
    sortOrder: 12,
    isSystem: true,
  },
];

export const DEFAULT_INCOME_CATEGORIES: Omit<Category, 'id' | 'createdAt'>[] = [
  {
    name: 'เงินเดือน',
    type: 'income',
    icon: '💵',
    color: 'category-family',
    sortOrder: 1,
    isSystem: true,
  },
  {
    name: 'โบนัส',
    type: 'income',
    icon: '🎁',
    color: 'category-entertainment',
    sortOrder: 2,
    isSystem: true,
  },
  {
    name: 'ค่าคอมมิชชั่น',
    type: 'income',
    icon: '💰',
    color: 'category-shopping',
    sortOrder: 3,
    isSystem: true,
  },
  {
    name: 'ดอกเบี้ย',
    type: 'income',
    icon: '🏦',
    color: 'category-bills',
    sortOrder: 4,
    isSystem: true,
  },
  {
    name: 'รายได้เสริม',
    type: 'income',
    icon: '✨',
    color: 'category-health',
    sortOrder: 5,
    isSystem: true,
  },
  {
    name: 'อื่นๆ',
    type: 'income',
    icon: '📥',
    color: 'category-other',
    sortOrder: 6,
    isSystem: true,
  },
];

export const CATEGORY_COLORS = {
  'category-food': 'bg-[oklch(var(--category-food)/0.15)] text-[oklch(var(--category-food))]',
  'category-shopping': 'bg-[oklch(var(--category-shopping)/0.15)] text-[oklch(var(--category-shopping))]',
  'category-transport': 'bg-[oklch(var(--category-transport)/0.15)] text-[oklch(var(--category-transport))]',
  'category-entertainment': 'bg-[oklch(var(--category-entertainment)/0.15)] text-[oklch(var(--category-entertainment))]',
  'category-health': 'bg-[oklch(var(--category-health)/0.15)] text-[oklch(var(--category-health))]',
  'category-bills': 'bg-[oklch(var(--category-bills)/0.15)] text-[oklch(var(--category-bills))]',
  'category-family': 'bg-[oklch(var(--category-family)/0.15)] text-[oklch(var(--category-family))]',
  'category-social': 'bg-[oklch(var(--category-social)/0.15)] text-[oklch(var(--category-social))]',
  'category-housing': 'bg-[oklch(var(--category-housing)/0.15)] text-[oklch(var(--category-housing))]',
  'category-communication': 'bg-[oklch(var(--category-communication)/0.15)] text-[oklch(var(--category-communication))]',
  'category-clothing': 'bg-[oklch(var(--category-clothing)/0.15)] text-[oklch(var(--category-clothing))]',
  'category-other': 'bg-[oklch(var(--category-other)/0.15)] text-[oklch(var(--category-other))]',
} as const;
